version: 0.0
os: linux
# destination에 아티팩트가 unzip된 결과가 생성될 디렉토리명을 넣어준다.
files:
  - source: ./
    destination: /home/ubuntu/build-fe
    overwrite: true
permissions:
  - object: ./
    pattern: '**'
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: ./scripts/beforeStart.sh
  AfterInstall:
    - location: ./scripts/start.sh
      timeout: 60
      runas: ubuntu
